#!/usr/bin/env bash
#Web servers are the piece of software generating and serving HTML pages, lets install one!
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start