#!/usr/bin/env bash
#Web servers are the piece of software generating and serving HTML pages!
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start