#!/usr/bin/env bash
#Infinity echo until interupt signal
touch /var/run/holbertonscript.pid
trap "echo I hate the kill command; rm -f /var/run/holbertonscript.pid" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm -f /var/run/holbertonscript.pid" SIGQUIT
x=0
while [ $x -lt 1 ]
do
    echo "To infinity and beyond"
    sleep 2
done