#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times except the 9th

x=1
while [ $x -lt 11 ]
do
	if [ $x == 9 ]
	then
	    echo "Holberton School"
	    echo "Hi"
	else
	    echo "Holberton School"
	fi
	(( x++ ))
done