#!/usr/bin/env bash
# This script is displaying good luck on 8th and bad luck on 4th iteration

x=1
while [ $x -lt 11 ]
do
    if [ $x == 4 ]
    then
	echo "bad luck"
    elif [ $x == 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    (( x++ ))
done