#!/usr/bin/env bash
# This script is displaying bad luck from x on the 4th, 9th and 17th iteration

x=1
while [ $x -lt 21 ]
do
    case $x in
	4)
	    echo $x
	    echo "bad luck from China"
	;;
	9)
	    echo $x
	    echo "bad luck from Japan"
	;;
	17)
	    echo $x
	    echo "bad luck from Italy"
	;;
	*)
	    echo $x
	    ;;
    esac
    (( x++ ))
done
