#!/usr/bin/env bash
#Script that changes home IP
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*$/127.0.0.2 localhost/' ~/hosts.new
sed -i '1s/^/8.8.8.8 facebook.com\n/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts