#!/usr/bin/env bash
#Script that configures the container so that Nginx is running as the nginx user
service nginx stop
chown -R nginx:nginx /etc/nginx
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u service nginx restart